mysite/forms/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'forms'
urlpatterns =[
    path('',views.index, name='mi_form'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forms/', include('forms.urls')),
]

mysite/forms/models.py
from django.db import models

# Create your models here.

class Usuarios(models.Model):
    nombre=models.CharField(max_length=15)
    telefono=models.CharField(max_length=15)
    fecha_de_nacimiento=models.DateField()
    email=models.EmailField(max_length=245)

mysite/forms/admin.py
from django.contrib import admin

# Register your models here.

mysite/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

mysite/forms/forms.py
from django import forms
from forms.models import Usuarios
from datetime import datetime


class RegistrarUsuario(forms.Form):
    nombre = forms.CharField(label='Nombre:',max_length=15,
                                    widget=forms.TextInput(
                                    attrs={
                                        'class':'form-control',
                                        'placeholder':'Nombre',
                                    }))
    telefono = forms.CharField(label='Teléfono',max_length=12,
                                    widget=forms.TextInput(
                                    attrs={
                                        'class':'form-control',
                                        'placeholder':'4421234567',
                                    }))
    fecha_de_nacimiento = forms.DateField(label='Fecha de nacimiento:',
                                    widget=forms.SelectDateWidget(years=range(1900,2001),
                                    attrs={
                                        'class':'form-control',
                                    }))
    email = forms.EmailField(label='Email:', max_length=245,
                             widget=forms.EmailInput(
                                 attrs={
                                     'class':'form-control',
                                     'placeholder':'ejemplo@ejemplo.com',
                                 }
                             ))
    
def registrar_usuario(self):
    fecha = datetime(int(self.data['fecha_de_nacimiento_year']),
                     int(self.data['fecha_de_nacimiento_month']),
                     int(self.data['fecha_de_nacimiento_day']))
        
    nuevo_usuario = Usuarios(nombre=self.data['nombre'],
                             telefono=self.data['telefono'],
                             fecha_de_nacimiento=fecha,
                             email=self.data['email'])
    nuevo_usuario.save()
    return 'Registro exitoso'

mysite/forms/tests.py
from django.test import TestCase

# Create your tests here.

mysite/forms/views.py
from django.shortcuts import render, redirect
from .forms import RegistrarUsuario
from .models import Usuarios

# Create your views here.

def index(request):
    mis_usuarios= Usuarios.objects.all()
    if request.method == 'POST':
       register_form = RegistrarUsuario(request.POST)
       if register_form.is_valid():
           success = register_form.registrar_usuario()
           return redirect('./')       
    else:
        #Muestra nuestro form
        register_form = RegistrarUsuario()
        return render(request, 'forms/mi_form.html',
                     {'register_form': register_form,
                      'usuarios': mis_usuarios})

    #register_form= RegistrarUsuario()
    #return render(request, 'forms/mi_form.html', {'register_form': register_form})

mysite/forms/templates/forms/mi_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <div class="container text-center pt-5">
    <h1>Hola</h1>
    <p>Mi tutorial de forms</p>
    <div class='jumbotron'>
      <center>
        <div class="text-left" style="max-width:500px">
          <form action="{% url 'forms:mi_form' %}" method="post">
            {% csrf_token %}
            {% for field in register_form %}
            <div class='form-group'>
              <label for="{{ field.name }}">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <br>
            <center><button type="submit" class="btn btn-success btn-lg">Registrar usuario</button></center>
          </form>
        </div>
      </center>
      <br>
<table  class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Fecha de nacimiento</th>
            <th>Email</th>
          </tr>
        </thead>
    <tbody>
          {% for user in usuarios %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.nombre }}</td>
            <td>{{ user.telefono }}</td>
            <td>{{ user.fecha_de_nacimiento }}</td>
            <td>{{ user.email }}</td>
          </tr>
          {% endfor %}
    </tbody>
  </table>
</div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>